backlight: aw99703: Remove unused variable
drivers/backlight/aw99703/leds_aw99703.c:705:27:
 error: variable 'bl_dev' set but not used [-Werror,-Wunused-but-set-variable]
  705 |         struct backlight_device *bl_dev;

Change-Id: Ic54933366a36805939160423188595c81e2711e6
Signed-off-by: Sevenrock <sevenrock@hotmail.de>